artifacts_root: artifacts 

data_ingestion:
    root_dir : artifacts/data_ingestion

data_validation:
    root_dir: artifacts/data_validation
    data_path: artifacts/data_ingestion/text.csv
    STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
    root_dir: artifacts/data_transformation
    data_path: artifacts/data_ingestion/text.csv
    transform_data_path: artifacts/data_transformation/text.csv

model_trainer:
    root_dir: artifacts/model_trainer
    data_path: artifacts/data_transformation/text.csv
    model : artifacts/model_trainer/model
    tokenizer_path: artifacts/model_trainer/tokenizer.pkl
    model_path: artifacts/model_trainer/model/model.keras
    

model_evaluation:
    root_dir: artifacts/model_evaluation
    data_path: artifacts/data_transformation/text.csv
    model_path: artifacts/model_trainer/model/model.keras
    tokenizer_path: artifacts/model_trainer/tokenizer.pkl
    mode_evaluation_path: artifacts/model_evaluation/model.keras
    matrix_path: artifacts/model_evaluation/metrix.json
    

prediction:
    model_path: artifacts/model_evaluation/model.keras
    tokenizer_path: artifacts/model_trainer/tokenizer.pkl