artifacts_root: artifacts 

data_ingestion:
    root_dir : artifacts/data_ingestion

data_validation:
    root_dir: artifacts/data_validation
    data_path: artifacts/data_ingestion/text.csv
    STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
    root_dir: artifacts/data_transformation